### ISSUE TITLE
60 minutes for address change

### ISSUE THREAD

**Issue by mcr** [core-wg/stateless#10]
section 2.2.2:
doc>  Since network addresses may change, a client SHOULD NOT assume that                                   
doc>   extended token lengths are supported by a server later than 60                                        
doc>   minutes after receiving the most-recent response with an extended                                     
 doc>  token length.                                                                                         

* 60 minutes for address changes?  Out of curiosity, upon what was this based?
  I lack a good deal of context, but this kind of feels like the kind of
  constant that will get baked into code and come to govern some behaviour
  that later might need updating.

**Comment by cabo** [comment]
The  number indeed sounds arbitrary.  We could make use of the parameter mechanics that RFC 7252 has (ACK_TIMEOUT and friends) and set the default to 1800 s.
