### ISSUE TITLE
look ma, no state!

### ISSUE THREAD

**Issue by mcr** [core-wg/stateless#9]
> ** Editorial nit:                                                                                      
> -- Figure 2 and 5. I would recommend replacing the                                                     
> colloquialism "look ma, no state!" with "no state".                                                    
                                                                                                         
One IESG member's nit is another IESG member's joy... <https://mailarchive.ietf.org/arch/msg/core/Y3SJGA 
_AwXWhldb6uORkicYuf5w/> I think I'm keeping it.

**Comment by cabo** [comment]
Given that this is in an illustrative figure, I tend to agree with Warren.

**Comment by mcr** [comment]
The WG likes the diagram as is.
